#!/usr/bin/env python3
"""Regenerate the publication list in research.html from citations.bib.

Standard library only, no dependencies. Run after editing citations.bib:
    python3 build_citations.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).parent
BIB_PATH = ROOT / "citations.bib"
HTML_PATH = ROOT / "research.html"

START_MARKER = "<!-- CITATIONS:START (generated by build_citations.py, do not edit by hand) -->"
END_MARKER = "<!-- CITATIONS:END -->"

MONTHS = {
    "jan": "Jan.", "feb": "Feb.", "mar": "Mar.", "apr": "Apr.",
    "may": "May", "jun": "Jun.", "jul": "Jul.", "aug": "Aug.",
    "sep": "Sep.", "oct": "Oct.", "nov": "Nov.", "dec": "Dec.",
}


def parse_bib(text):
    text = "\n".join(l for l in text.splitlines() if not l.strip().startswith("%"))
    entries = []
    for m in re.finditer(r"@(\w+)\s*\{\s*([^,]+),(.*?)\n\}", text, re.DOTALL):
        entry_type, key, body = m.group(1), m.group(2).strip(), m.group(3)
        fields = dict(re.findall(r"(\w+)\s*=\s*\{([^}]*)\}", body, re.DOTALL))
        fields = {k: " ".join(v.split()) for k, v in fields.items()}
        entries.append((entry_type, key, fields))
    return entries


def format_entry(entry_type, key, f):
    required = ("author", "title", "booktitle", "year", "url")
    missing = [k for k in required if k not in f]
    if missing:
        raise ValueError(f"entry '{key}' missing required field(s): {', '.join(missing)}")

    note = f.get("note")
    is_oral = bool(note) and note.strip().lower() == "oral presentation"
    trailing_note = note if note and not is_oral else None

    prefix = "oral presentation at the" if is_oral else "in"
    venue = f'<a href="{f["url"]}">{f["booktitle"]}</a>'

    tail_parts = []
    if "series" in f:
        tail_parts.append(f'ser. {f["series"]}')
    if "organization" in f:
        tail_parts.append(f["organization"])
    if "publisher" in f:
        tail_parts.append(f["publisher"])
    if "address" in f:
        tail_parts.append(f["address"])
    if "month" in f:
        month = MONTHS.get(f["month"].lower(), f["month"])
        tail_parts.append(f'{month} {f["year"]}')
    else:
        tail_parts.append(f["year"])
    if trailing_note:
        tail_parts.append(trailing_note[0].lower() + trailing_note[1:])
    tail = ", ".join(tail_parts)

    return f'{f["author"]}, "{f["title"]}," {prefix} {venue}, {tail}.'


def render_list(entries):
    lines = ["      <ul>"]
    for entry_type, key, fields in entries:
        text = format_entry(entry_type, key, fields)
        lines.append("        <li>")
        lines.append(f"          {text}")
        lines.append("        </li>")
    lines.append("      </ul>")
    return "\n".join(lines)


def main():
    entries = parse_bib(BIB_PATH.read_text(encoding="utf-8"))
    new_list = render_list(entries)

    html = HTML_PATH.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL
    )
    replacement = f"{START_MARKER}\n{new_list}\n      {END_MARKER}"
    if not pattern.search(html):
        raise SystemExit(
            f"Could not find {START_MARKER!r} / {END_MARKER!r} markers in research.html"
        )
    html = pattern.sub(replacement, html)
    HTML_PATH.write_text(html, encoding="utf-8")
    print(f"Wrote {len(entries)} citation(s) to {HTML_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
